### ISSUE TITLE
Session header is Yuge on smaller devices

### ISSUE THREAD

**Issue by alexmoore** [karnett/CodeMashiOS#3]
On my iPhone 5s, the header for the sessions section takes up half the screen. I don’t know if this was intended or not, but you could only see two sessions at a time. 

![37bf365e-4515-4cd5-84c9-1f3b7a8e3f8d](https://user-images.githubusercontent.com/1438/34523036-aa0b40ea-f063-11e7-9252-fa23f57c61c4.png)

**Comment by karnett** [comment]
LOL That's beautiful.. Thank you for submitting @alexmoore!

**Comment by alexmoore** [comment]
I've since upgraded to an 8+, so not sure if this is an issue anymore 🤷‍♂️
